const botswana = [
  {name: "0", type: "Elephant", suit: "elephant", value: 0, url: "https://furtivespy.com/images/botswana/botswana_0_0.png"},
  {name: "1", type: "Elephant", suit: "elephant", value: 1, url: "https://furtivespy.com/images/botswana/botswana_0_1.png"},
  {name: "2", type: "Elephant", suit: "elephant", value: 2, url: "https://furtivespy.com/images/botswana/botswana_0_2.png"},
  {name: "3", type: "Elephant", suit: "elephant", value: 3, url: "https://furtivespy.com/images/botswana/botswana_0_3.png"},
  {name: "4", type: "Elephant", suit: "elephant", value: 4, url: "https://furtivespy.com/images/botswana/botswana_0_4.png"},
  {name: "5", type: "Elephant", suit: "elephant", value: 5, url: "https://furtivespy.com/images/botswana/botswana_0_5.png"},
  {name: "0", type: "Meerkat", suit: "meerkat", value: 0, url: "https://furtivespy.com/images/botswana/botswana_1_0.png"},
  {name: "1", type: "Meerkat", suit: "meerkat", value: 1, url: "https://furtivespy.com/images/botswana/botswana_1_1.png"},
  {name: "2", type: "Meerkat", suit: "meerkat", value: 2, url: "https://furtivespy.com/images/botswana/botswana_1_2.png"},
  {name: "3", type: "Meerkat", suit: "meerkat", value: 3, url: "https://furtivespy.com/images/botswana/botswana_1_3.png"},
  {name: "4", type: "Meerkat", suit: "meerkat", value: 4, url: "https://furtivespy.com/images/botswana/botswana_1_4.png"},
  {name: "5", type: "Meerkat", suit: "meerkat", value: 5, url: "https://furtivespy.com/images/botswana/botswana_1_5.png"},
  {name: "0", type: "Lion", suit: "lion", value: 0, url: "https://furtivespy.com/images/botswana/botswana_2_0.png"},
  {name: "1", type: "Lion", suit: "lion", value: 1, url: "https://furtivespy.com/images/botswana/botswana_2_1.png"},
  {name: "2", type: "Lion", suit: "lion", value: 2, url: "https://furtivespy.com/images/botswana/botswana_2_2.png"},
  {name: "3", type: "Lion", suit: "lion", value: 3, url: "https://furtivespy.com/images/botswana/botswana_2_3.png"},
  {name: "4", type: "Lion", suit: "lion", value: 4, url: "https://furtivespy.com/images/botswana/botswana_2_4.png"},
  {name: "5", type: "Lion", suit: "lion", value: 5, url: "https://furtivespy.com/images/botswana/botswana_2_5.png"},
  {name: "0", type: "Hippo", suit: "hippo", value: 0, url: "https://furtivespy.com/images/botswana/botswana_3_0.png"},
  {name: "1", type: "Hippo", suit: "hippo", value: 1, url: "https://furtivespy.com/images/botswana/botswana_3_1.png"},
  {name: "2", type: "Hippo", suit: "hippo", value: 2, url: "https://furtivespy.com/images/botswana/botswana_3_2.png"},
  {name: "3", type: "Hippo", suit: "hippo", value: 3, url: "https://furtivespy.com/images/botswana/botswana_3_3.png"},
  {name: "4", type: "Hippo", suit: "hippo", value: 4, url: "https://furtivespy.com/images/botswana/botswana_3_4.png"},
  {name: "5", type: "Hippo", suit: "hippo", value: 5, url: "https://furtivespy.com/images/botswana/botswana_3_5.png"},
  {name: "0", type: "Giraffe", suit: "giraffe", value: 0, url: "https://furtivespy.com/images/botswana/botswana_4_0.png"},
  {name: "1", type: "Giraffe", suit: "giraffe", value: 1, url: "https://furtivespy.com/images/botswana/botswana_4_1.png"},
  {name: "2", type: "Giraffe", suit: "giraffe", value: 2, url: "https://furtivespy.com/images/botswana/botswana_4_2.png"},
  {name: "3", type: "Giraffe", suit: "giraffe", value: 3, url: "https://furtivespy.com/images/botswana/botswana_4_3.png"},
  {name: "4", type: "Giraffe", suit: "giraffe", value: 4, url: "https://furtivespy.com/images/botswana/botswana_4_4.png"},
  {name: "5", type: "Giraffe", suit: "giraffe", value: 5, url: "https://furtivespy.com/images/botswana/botswana_4_5.png"},
]

module.exports = botswana;
