const brassBase = [
  {name: "Belper", type: "Location", suit: "a", url: "https://furtivespy.com/images/brass/belper.png"},
  {name: "Derby", type: "Location", suit: "a", url: "https://furtivespy.com/images/brass/derby.png"},
  {name: "Leek", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/leek.png"},
  {name: "Stoke-on-Trent", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stoke.png"},
  {name: "Stone", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stone.png"},
  {name: "Uttoxeter", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/uttoxeter.png"},
  {name: "Stafford", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/stafford.png"},
  {name: "Burton-on-Trent", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/burton.png"},
  {name: "Cannock", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/cannock.png"},
  {name: "Tamworth", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/tamworth.png"},
  {name: "Walsall", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/walsall.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Dudley", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/dudley.png"},
  {name: "Kidderminster", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/kidderminster.png"},
  {name: "Wolverhampton", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/wolverhampton.png"},
  {name: "Worcester", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/worcester.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Nuneaton", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/nuneaton.png"},
  {name: "Reddich", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/reddich.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-1.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},

  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
]

const brassTwoPlayer = [
  {name: "Stafford", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/stafford.png"},
  {name: "Stafford", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/stafford.png"},
  {name: "Burton-on-Trent", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/burton.png"},
  {name: "Burton-on-Trent", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/burton.png"},
  {name: "Cannock", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/cannock.png"},
  {name: "Cannock", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/cannock.png"},
  {name: "Tamworth", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/tamworth.png"},
  {name: "Walsall", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/walsall.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Dudley", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/dudley.png"},
  {name: "Dudley", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/dudley.png"},
  {name: "Kidderminster", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/kidderminster.png"},
  {name: "Kidderminster", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/kidderminster.png"},
  {name: "Wolverhampton", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/wolverhampton.png"},
  {name: "Wolverhampton", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/wolverhampton.png"},
  {name: "Worcester", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/worcester.png"},
  {name: "Worcester", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/worcester.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Nuneaton", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/nuneaton.png"},
  {name: "Reddich", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/reddich.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
]

const brassThreePlayer = [
  {name: "Leek", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/leek.png"},
  {name: "Leek", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/leek.png"},
  {name: "Stoke-on-Trent", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stoke.png"},
  {name: "Stoke-on-Trent", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stoke.png"},
  {name: "Stoke-on-Trent", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stoke.png"},
  {name: "Stone", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stone.png"},
  {name: "Stone", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stone.png"},
  {name: "Uttoxeter", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/uttoxeter.png"},
  {name: "Stafford", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/stafford.png"},
  {name: "Stafford", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/stafford.png"},
  {name: "Burton-on-Trent", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/burton.png"},
  {name: "Burton-on-Trent", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/burton.png"},
  {name: "Cannock", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/cannock.png"},
  {name: "Cannock", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/cannock.png"},
  {name: "Tamworth", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/tamworth.png"},
  {name: "Walsall", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/walsall.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Dudley", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/dudley.png"},
  {name: "Dudley", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/dudley.png"},
  {name: "Kidderminster", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/kidderminster.png"},
  {name: "Kidderminster", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/kidderminster.png"},
  {name: "Wolverhampton", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/wolverhampton.png"},
  {name: "Wolverhampton", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/wolverhampton.png"},
  {name: "Worcester", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/worcester.png"},
  {name: "Worcester", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/worcester.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Nuneaton", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/nuneaton.png"},
  {name: "Reddich", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/reddich.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-1.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-2.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-3.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-1.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-2.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-3.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
]

const brassFourPlayer = [
  {name: "Belper", type: "Location", suit: "a", url: "https://furtivespy.com/images/brass/belper.png"},
  {name: "Belper", type: "Location", suit: "a", url: "https://furtivespy.com/images/brass/belper.png"},
  {name: "Derby", type: "Location", suit: "a", url: "https://furtivespy.com/images/brass/derby.png"},
  {name: "Derby", type: "Location", suit: "a", url: "https://furtivespy.com/images/brass/derby.png"},
  {name: "Derby", type: "Location", suit: "a", url: "https://furtivespy.com/images/brass/derby.png"},
  {name: "Leek", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/leek.png"},
  {name: "Leek", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/leek.png"},
  {name: "Stoke-on-Trent", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stoke.png"},
  {name: "Stoke-on-Trent", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stoke.png"},
  {name: "Stoke-on-Trent", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stoke.png"},
  {name: "Stone", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stone.png"},
  {name: "Stone", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/stone.png"},
  {name: "Uttoxeter", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/uttoxeter.png"},
  {name: "Uttoxeter", type: "Location", suit: "b", url: "https://furtivespy.com/images/brass/uttoxeter.png"},
  {name: "Stafford", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/stafford.png"},
  {name: "Stafford", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/stafford.png"},
  {name: "Burton-on-Trent", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/burton.png"},
  {name: "Burton-on-Trent", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/burton.png"},
  {name: "Cannock", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/cannock.png"},
  {name: "Cannock", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/cannock.png"},
  {name: "Tamworth", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/tamworth.png"},
  {name: "Walsall", type: "Location", suit: "c", url: "https://furtivespy.com/images/brass/walsall.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Coalbrookdale", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/coalbrookdale.png"},
  {name: "Dudley", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/dudley.png"},
  {name: "Dudley", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/dudley.png"},
  {name: "Kidderminster", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/kidderminster.png"},
  {name: "Kidderminster", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/kidderminster.png"},
  {name: "Wolverhampton", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/wolverhampton.png"},
  {name: "Wolverhampton", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/wolverhampton.png"},
  {name: "Worcester", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/worcester.png"},
  {name: "Worcester", type: "Location", suit: "d", url: "https://furtivespy.com/images/brass/worcester.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Birmingham", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/birmingham.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Coventry", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/coventry.png"},
  {name: "Nuneaton", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/nuneaton.png"},
  {name: "Reddich", type: "Location", suit: "e", url: "https://furtivespy.com/images/brass/reddich.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Iron Works", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/iron.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Coal Mine", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/coal.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-1.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-1.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-2.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-2.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-3.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-1.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-2.png"},
  {name: "Manufactured Goods / Cotton Mill", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/goods-mill-3.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Pottery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/pottery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
  {name: "Brewery", type: "Industry", suit: "f", url: "https://furtivespy.com/images/brass/brewery.png"},
]

const brassWildLocation = [
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
  {name: "Wild Location", type: "Location", suit: "g", url: "https://furtivespy.com/images/brass/wild-location.png"},
]

const brassWildIndustry = [
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
  {name: "Wild Industry", type: "Industry", suit: "h", url: "https://furtivespy.com/images/brass/wild-industry.png"},    
]

module.exports = { brassBase, brassTwoPlayer, brassThreePlayer, brassFourPlayer, brassWildLocation, brassWildIndustry }