const brianBoru = [
  {name: "1", type: "🟡", suit: "none", value: 1, url: "https://furtivespy.com/images/brian/bb01.png"},
  {name: "2", type: "🔴", suit: "none", value: 2, url: "https://furtivespy.com/images/brian/bb02.png"},
  {name: "3", type: "🔵", suit: "none", value: 3, url: "https://furtivespy.com/images/brian/bb03.png"},
  {name: "4", type: "🟡", suit: "none", value: 4, url: "https://furtivespy.com/images/brian/bb04.png"},
  {name: "5", type: "🔴", suit: "none", value: 5, url: "https://furtivespy.com/images/brian/bb05.png"},
  {name: "6", type: "🔵", suit: "none", value: 6, url: "https://furtivespy.com/images/brian/bb06.png"},
  {name: "7", type: "🟡", suit: "none", value: 7, url: "https://furtivespy.com/images/brian/bb07.png"},
  {name: "8", type: "🔴", suit: "none", value: 8, url: "https://furtivespy.com/images/brian/bb08.png"},
  {name: "9", type: "🔵", suit: "none", value: 9, url: "https://furtivespy.com/images/brian/bb09.png"},
  {name: "10", type: "🟡", suit: "none", value: 10, url: "https://furtivespy.com/images/brian/bb10.png"},
  {name: "11", type: "🔴", suit: "none", value: 11, url: "https://furtivespy.com/images/brian/bb11.png"},
  {name: "12", type: "🔵", suit: "none", value: 12, url: "https://furtivespy.com/images/brian/bb12.png"},
  {name: "13", type: "⚪", suit: "none", value: 13, url: "https://furtivespy.com/images/brian/bb13.png"},
  {name: "14", type: "🟡", suit: "none", value: 14, url: "https://furtivespy.com/images/brian/bb14.png"},
  {name: "15", type: "🔴", suit: "none", value: 15, url: "https://furtivespy.com/images/brian/bb15.png"},
  {name: "16", type: "🔵", suit: "none", value: 16, url: "https://furtivespy.com/images/brian/bb16.png"},
  {name: "17", type: "🟡", suit: "none", value: 17, url: "https://furtivespy.com/images/brian/bb17.png"},
  {name: "18", type: "🔴", suit: "none", value: 18, url: "https://furtivespy.com/images/brian/bb18.png"},
  {name: "19", type: "🔵", suit: "none", value: 19, url: "https://furtivespy.com/images/brian/bb19.png"},
  {name: "20", type: "⚪", suit: "none", value: 20, url: "https://furtivespy.com/images/brian/bb20.png"},
  {name: "21", type: "⚪", suit: "none", value: 21, url: "https://furtivespy.com/images/brian/bb21.png"},
  {name: "22", type: "⚪", suit: "none", value: 22, url: "https://furtivespy.com/images/brian/bb22.png"},
  {name: "23", type: "🟡", suit: "none", value: 23, url: "https://furtivespy.com/images/brian/bb23.png"},
  {name: "24", type: "🔴", suit: "none", value: 24, url: "https://furtivespy.com/images/brian/bb24.png"},
  {name: "25", type: "🔵", suit: "none", value: 25, url: "https://furtivespy.com/images/brian/bb25.png"},
]

module.exports = brianBoru;
