const heatBase = [
  {name: `1`, value: 1, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_1.png`},
  {name: `1`, value: 1, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_1.png`},
  {name: `1`, value: 1, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_1.png`},
  {name: `2`, value: 2, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_2.png`},
  {name: `2`, value: 2, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_2.png`},
  {name: `2`, value: 2, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_2.png`},
  {name: `3`, value: 3, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_3.png`},
  {name: `3`, value: 3, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_3.png`},
  {name: `3`, value: 3, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_3.png`},
  {name: `4`, value: 4, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_4.png`},
  {name: `4`, value: 4, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_4.png`},
  {name: `4`, value: 4, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_4.png`},
  
  {name: `Stress`, value: 1, type: `Engine`, suit: `b`, url: `https://furtivespy.com/images/heat/stress.png`},
  {name: `Stress`, value: 1, type: `Engine`, suit: `b`, url: `https://furtivespy.com/images/heat/stress.png`},
  {name: `Stress`, value: 1, type: `Engine`, suit: `b`, url: `https://furtivespy.com/images/heat/stress.png`},
]

const heatGeneric = [
  {name: `Heat`, value: 0, type: `Engine`, suit: `a`, url: `https://furtivespy.com/images/heat/heat.png`},
  {name: `Stress`, value: 1, type: `Engine`, suit: `b`, url: `https://furtivespy.com/images/heat/stress.png`},
  {name: `5`, value: 5, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_5.png`},
  {name: `0`, value: 0, type: `Speed`, suit: `h`, url: `https://furtivespy.com/images/heat/heat_0.png`},
  {name: `Heat (Base)`, value: 0, type: `Engine`, suit: `a`, url: `https://furtivespy.com/images/heat/heat_heat.png`},
]

const heatUpgrades = [
  {name: `4 Wheel Drive (+++)`, value: 0, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/4wheeldrive+.png`},
  {name: `4 Wheel Drive (+)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/4wheeldrive.png`},
  {name: `4 Wheel Drive (4+)`, value: 4, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/4wheeldrive4.png`},
  {name: `4 Wheel Drive (+Cooling)`, value: 0, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/4wheeldrivecool.png`},
  {name: `Body (1)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/body1.png`},
  {name: `Body (2 & Slipstream)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/body2.png`},
  {name: `Body (2 & Cooling)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/body2b.png`},
  {name: `Body (3)`, value: 3, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/body3.png`},
  {name: `Body (5)`, value: 5, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/body5.png`},
  {name: `Body (6)`, value: 6, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/body6.png`},
  {name: `Brakes (1|2|3|4)`, value: 4, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/brakes1234.png`},
  {name: `Brakes (1|3)`, value: 3, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/brakes13.png`},
  {name: `Brakes (1|5)`, value: 5, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/brakes15.png`},
  {name: `Brakes (2|4)`, value: 4, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/brakes24.png`},
  {name: `Cooling System (1)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/cooling1.png`},
  {name: `Cooling System (3)`, value: 3, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/cooling3.png`},
  {name: `Cooling System (4)`, value: 4, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/cooling4.png`},
  {name: `Cooling System (6)`, value: 6, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/cooling6.png`},
  {name: `Fuel (+)`, value: 0, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/fuel.png`},
  {name: `Fuel (2)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/fuel2.png`},
  {name: `Gas Pedal (1+)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/gaspedal1+.png`},
  {name: `Gas Pedal (1)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/gaspedal1.png`},
  {name: `Gas Pedal (2)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/gaspedal2.png`},
  {name: `Gas Pedal (3)`, value: 3, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/gaspedal3.png`},
  {name: `Gas Pedal (4)`, value: 4, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/gaspedal4.png`},
  {name: `R.P.M. (+, +3)`, value: 0, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/rpm+.png`},
  {name: `R.P.M. (1, +3)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/rpm1.png`},
  {name: `R.P.M. (1|2, +1)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/rpm12.png`},
  {name: `R.P.M. (1, +2)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/rpm1b.png`},
  {name: `R.P.M. (2, +2)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/rpm2.png`},
  {name: `R.P.M. (3, +2)`, value: 3, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/rpm3.png`},
  {name: `Suspension (1)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/suspension1.png`},
  {name: `Suspension (2 & Cooling)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/suspension2.png`},
  {name: `Suspension (2)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/suspension2b.png`},
  {name: `Suspension (4)`, value: 4, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/suspension4.png`},
  {name: `Tires (++)`, value: 0, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/tires+.png`},
  {name: `Tires (+)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/tires.png`},
  {name: `Tires (1)`, value: 1, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/tires1.png`},
  {name: `Tires (2)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/tires2.png`},
  {name: `Tires (2 & Cooling)`, value: 2, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/tires2b.png`},
  {name: `Tires (3)`, value: 3, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/tires3.png`},
  {name: `Turbo Charger (8)`, value: 8, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/turbo8.png`},
  {name: `Turbo Charger (7)`, value: 7, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/turby7.png`},
  {name: `Wings (3)`, value: 3, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/wings3.png`},
  {name: `Wings (4)`, value: 4, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/wings4.png`},
  {name: `Wings (6)`, value: 6, type: `Upgrade`, suit: `d`, url: `https://furtivespy.com/images/heat/wings6.png`},
]

module.exports = {heatBase, heatGeneric, heatUpgrades};