
const mollyVice = [
  {name: "1", type: "Fans", suit: "fans", value: 1, url: "https://furtivespy.com/images/mollyhouse/cards_0_0.png"},
  {name: "2", type: "Fans", suit: "fans", value: 2, url: "https://furtivespy.com/images/mollyhouse/cards_0_1.png"},
  {name: "3", type: "Fans", suit: "fans", value: 3, url: "https://furtivespy.com/images/mollyhouse/cards_0_2.png"},
  {name: "4", type: "Fans", suit: "fans", value: 4, url: "https://furtivespy.com/images/mollyhouse/cards_0_3.png"},
  {name: "5", type: "Fans", suit: "fans", value: 5, url: "https://furtivespy.com/images/mollyhouse/cards_0_4.png"},
  {name: "6", type: "Fans", suit: "fans", value: 6, url: "https://furtivespy.com/images/mollyhouse/cards_0_5.png"},
  {name: "7", type: "Fans", suit: "fans", value: 7, url: "https://furtivespy.com/images/mollyhouse/cards_0_6.png"},
  {name: "8", type: "Fans", suit: "fans", value: 8, url: "https://furtivespy.com/images/mollyhouse/cards_0_7.png"},
  {name: "9", type: "Fans", suit: "fans", value: 9, url: "https://furtivespy.com/images/mollyhouse/cards_0_8.png"},
  {name: "Queen", type: "Fans", suit: "fans", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_0_9.png"},
  {name: "Jack", type: "Fans", suit: "fans", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_1_0.png"},
  {name: "Rogue", type: "Fans", suit: "fans", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_1_1.png"},
  {name: "Constable", type: "Fans", suit: "fans", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_1_2.png"},
  
  {name: "1", type: "Cups", suit: "cups", value: 1, url: "https://furtivespy.com/images/mollyhouse/cards_1_3.png"},
  {name: "2", type: "Cups", suit: "cups", value: 2, url: "https://furtivespy.com/images/mollyhouse/cards_1_4.png"},
  {name: "3", type: "Cups", suit: "cups", value: 3, url: "https://furtivespy.com/images/mollyhouse/cards_1_5.png"},
  {name: "4", type: "Cups", suit: "cups", value: 4, url: "https://furtivespy.com/images/mollyhouse/cards_1_6.png"},
  {name: "5", type: "Cups", suit: "cups", value: 5, url: "https://furtivespy.com/images/mollyhouse/cards_1_7.png"},
  {name: "6", type: "Cups", suit: "cups", value: 6, url: "https://furtivespy.com/images/mollyhouse/cards_1_8.png"},
  {name: "7", type: "Cups", suit: "cups", value: 7, url: "https://furtivespy.com/images/mollyhouse/cards_1_9.png"},
  {name: "8", type: "Cups", suit: "cups", value: 8, url: "https://furtivespy.com/images/mollyhouse/cards_2_0.png"},
  {name: "9", type: "Cups", suit: "cups", value: 9, url: "https://furtivespy.com/images/mollyhouse/cards_2_1.png"},
  {name: "Queen", type: "Cups", suit: "cups", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_2_2.png"},
  {name: "Jack", type: "Cups", suit: "cups", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_2_3.png"},
  {name: "Rogue", type: "Cups", suit: "cups", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_2_4.png"},
  {name: "Constable", type: "Cups", suit: "cups", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_2_5.png"},

  {name: "1", type: "Pentacles", suit: "pentacles", value: 1, url: "https://furtivespy.com/images/mollyhouse/cards_2_6.png"},
  {name: "2", type: "Pentacles", suit: "pentacles", value: 2, url: "https://furtivespy.com/images/mollyhouse/cards_2_7.png"},
  {name: "3", type: "Pentacles", suit: "pentacles", value: 3, url: "https://furtivespy.com/images/mollyhouse/cards_2_8.png"},
  {name: "4", type: "Pentacles", suit: "pentacles", value: 4, url: "https://furtivespy.com/images/mollyhouse/cards_2_9.png"},
  {name: "5", type: "Pentacles", suit: "pentacles", value: 5, url: "https://furtivespy.com/images/mollyhouse/cards_3_0.png"},
  {name: "6", type: "Pentacles", suit: "pentacles", value: 6, url: "https://furtivespy.com/images/mollyhouse/cards_3_1.png"},
  {name: "7", type: "Pentacles", suit: "pentacles", value: 7, url: "https://furtivespy.com/images/mollyhouse/cards_3_2.png"},
  {name: "8", type: "Pentacles", suit: "pentacles", value: 8, url: "https://furtivespy.com/images/mollyhouse/cards_3_3.png"},
  {name: "9", type: "Pentacles", suit: "pentacles", value: 9, url: "https://furtivespy.com/images/mollyhouse/cards_3_4.png"},
  {name: "Queen", type: "Pentacles", suit: "pentacles", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_3_5.png"},
  {name: "Jack", type: "Pentacles", suit: "pentacles", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_3_6.png"},
  {name: "Rogue", type: "Pentacles", suit: "pentacles", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_3_7.png"},
  {name: "Constable", type: "Pentacles", suit: "pentacles", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_3_8.png"},

  {name: "1", type: "Hearts", suit: "hearts", value: 1, url: "https://furtivespy.com/images/mollyhouse/cards_3_9.png"},
  {name: "2", type: "Hearts", suit: "hearts", value: 2, url: "https://furtivespy.com/images/mollyhouse/cards_4_0.png"},
  {name: "3", type: "Hearts", suit: "hearts", value: 3, url: "https://furtivespy.com/images/mollyhouse/cards_4_1.png"},
  {name: "4", type: "Hearts", suit: "hearts", value: 4, url: "https://furtivespy.com/images/mollyhouse/cards_4_2.png"},
  {name: "5", type: "Hearts", suit: "hearts", value: 5, url: "https://furtivespy.com/images/mollyhouse/cards_4_3.png"},
  {name: "6", type: "Hearts", suit: "hearts", value: 6, url: "https://furtivespy.com/images/mollyhouse/cards_4_4.png"},
  {name: "7", type: "Hearts", suit: "hearts", value: 7, url: "https://furtivespy.com/images/mollyhouse/cards_4_5.png"},
  {name: "8", type: "Hearts", suit: "hearts", value: 8, url: "https://furtivespy.com/images/mollyhouse/cards_4_6.png"},
  {name: "9", type: "Hearts", suit: "hearts", value: 9, url: "https://furtivespy.com/images/mollyhouse/cards_4_7.png"},
  {name: "Queen", type: "Hearts", suit: "hearts", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_4_8.png"},
  {name: "Jack", type: "Hearts", suit: "hearts", value: 10, url: "https://furtivespy.com/images/mollyhouse/cards_4_9.png"},
  {name: "Rogue", type: "Hearts", suit: "hearts", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_5_0.png"},
  {name: "Constable", type: "Hearts", suit: "hearts", value: 0, url: "https://furtivespy.com/images/mollyhouse/cards_5_1.png"},
]

const mollyLoyalty = [
  {name: "Loyal", type: "Yellow", suit: "yellow", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_0_0.png"},
  {name: "Loyal", type: "Yellow", suit: "yellow", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_0_1.png"},
  {name: "Loyal", type: "Yellow", suit: "yellow", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_0_2.png"},
  {name: "Informer!", type: "Yellow", suit: "yellow", value: 3, url: "https://furtivespy.com/images/mollyhouse/loyal_0_3.png"},
  {name: "Loyal", type: "Blue", suit: "blue", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_1_0.png"},
  {name: "Loyal", type: "Blue", suit: "blue", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_1_1.png"},
  {name: "Loyal", type: "Blue", suit: "blue", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_1_2.png"},
  {name: "Informer!", type: "Blue", suit: "blue", value: 3, url: "https://furtivespy.com/images/mollyhouse/loyal_1_3.png"},
  {name: "Loyal", type: "Purple", suit: "purple", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_2_0.png"},
  {name: "Loyal", type: "Purple", suit: "purple", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_2_1.png"},
  {name: "Loyal", type: "Purple", suit: "purple", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_2_2.png"},
  {name: "Informer!", type: "Purple", suit: "purple", value: 3, url: "https://furtivespy.com/images/mollyhouse/loyal_2_3.png"},
  {name: "Loyal", type: "Green", suit: "green", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_3_0.png"},
  {name: "Loyal", type: "Green", suit: "green", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_3_1.png"},
  {name: "Loyal", type: "Green", suit: "green", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_3_2.png"},
  {name: "Informer!", type: "Green", suit: "green", value: 3, url: "https://furtivespy.com/images/mollyhouse/loyal_3_3.png"},
  {name: "Loyal", type: "Pink", suit: "pink", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_4_0.png"},
  {name: "Loyal", type: "Pink", suit: "pink", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_4_1.png"},
  {name: "Loyal", type: "Pink", suit: "pink", value: 2, url: "https://furtivespy.com/images/mollyhouse/loyal_4_2.png"},
  {name: "Informer!", type: "Pink", suit: "pink", value: 3, url: "https://furtivespy.com/images/mollyhouse/loyal_4_3.png"},
]

const mollyMinor = [
  {name: "Misdemeanor: Sodomy", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_0_0.png"},
  {name: "Attempted Sodomy", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_0_1.png"},
  {name: "Assault & Attempted Sodomy", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_0_2.png"},
  {name: "Assault & Sodomy Intent", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_0_3.png"},
  {name: "Assaulting a Person Unknown", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_0_4.png"},
  {name: "Disorderly House", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_0_5.png"},
  {name: "Keeping a House to encourage Sodomy", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_1_0.png"},
  {name: "Sodomitical Practices", type: "Minor Indictment", suit: "minor", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_1_1.png"}, 
]

const mollyMajor = [
  {name: "Assaulting a Constable", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_1_2.png"},
  {name: "Assaulting an Informer", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_1_3.png"},
  {name: "Indecent Postures", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_1_4.png"},
  {name: "Feloniously, Wickedly, & Devilishly", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_1_5.png"},
  {name: "Feloniously Committing Sodomy", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_2_0.png"},
  {name: "Not Having God Before Their Eyes", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_2_1.png"},
  {name: "Sodomy", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_2_2.png"},
  {name: "Buggery", type: "Major Indictment", suit: "major", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_2_3.png"},
]

const mollyItem = [
  {name: "Newspaper Notice", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_2_4.png"},
  {name: "Newspaper Notice", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_2_5.png"},
  {name: "Newspaper Notice", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_3_0.png"},
  {name: "Bribe", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_3_1.png"},
  {name: "Bribe", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_3_2.png"},
  {name: "Bribe", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_3_3.png"},
  {name: "Violin", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_3_4.png"},
  {name: "Violin", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_3_5.png"},
  {name: "Violin", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_4_0.png"},
  {name: "Domino", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_4_1.png"},
  {name: "Domino", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_4_2.png"},
  {name: "Domino", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_4_3.png"},
  {name: "Bottle of Gin", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_4_4.png"},
  {name: "Bottle of Gin", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_4_5.png"},
  {name: "Bottle of Gin", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_5_0.png"},
  {name: "Bottle of Gin", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_5_1.png"},
  {name: "Dress of Cups", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_5_2.png"},
  {name: "Dress of Fans", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_5_3.png"},
  {name: "Dress of Hearts", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_5_4.png"},
  {name: "Dress of Pentacles", type: "Item", suit: "item", value: 1, url: "https://furtivespy.com/images/mollyhouse/other_5_5.png"},
]

module.exports = {mollyVice, mollyLoyalty, mollyMinor, mollyMajor, mollyItem};
