const playingCards = [
  {name: "A", type: "♣", suit: "clubs", value: 1},
  {name: "2", type: "♣", suit: "clubs", value: 2},
  {name: "3", type: "♣", suit: "clubs", value: 3},
  {name: "4", type: "♣", suit: "clubs", value: 4},
  {name: "5", type: "♣", suit: "clubs", value: 5},
  {name: "6", type: "♣", suit: "clubs", value: 6},
  {name: "7", type: "♣", suit: "clubs", value: 7},
  {name: "8", type: "♣", suit: "clubs", value: 8},
  {name: "9", type: "♣", suit: "clubs", value: 9},
  {name: "10", type: "♣", suit: "clubs", value: 10},
  {name: "J", type: "♣", suit: "clubs", value: 11},
  {name: "Q", type: "♣", suit: "clubs", value: 12},
  {name: "K", type: "♣", suit: "clubs", value: 13},

  {name: "A", type: "♦", suit: "diamonds", value: 1},
  {name: "2", type: "♦", suit: "diamonds", value: 2},
  {name: "3", type: "♦", suit: "diamonds", value: 3},
  {name: "4", type: "♦", suit: "diamonds", value: 4},
  {name: "5", type: "♦", suit: "diamonds", value: 5},
  {name: "6", type: "♦", suit: "diamonds", value: 6},
  {name: "7", type: "♦", suit: "diamonds", value: 7},
  {name: "8", type: "♦", suit: "diamonds", value: 8},
  {name: "9", type: "♦", suit: "diamonds", value: 9},
  {name: "10", type: "♦", suit: "diamonds", value: 10},
  {name: "J", type: "♦", suit: "diamonds", value: 11},
  {name: "Q", type: "♦", suit: "diamonds", value: 12},
  {name: "K", type: "♦", suit: "diamonds", value: 13},

  {name: "A", type: "♥", suit: "hearts", value: 1},
  {name: "2", type: "♥", suit: "hearts", value: 2},
  {name: "3", type: "♥", suit: "hearts", value: 3},
  {name: "4", type: "♥", suit: "hearts", value: 4},
  {name: "5", type: "♥", suit: "hearts", value: 5},
  {name: "6", type: "♥", suit: "hearts", value: 6},
  {name: "7", type: "♥", suit: "hearts", value: 7},
  {name: "8", type: "♥", suit: "hearts", value: 8},
  {name: "9", type: "♥", suit: "hearts", value: 9},
  {name: "10", type: "♥", suit: "hearts", value: 10},
  {name: "J", type: "♥", suit: "hearts", value: 11},
  {name: "Q", type: "♥", suit: "hearts", value: 12},
  {name: "K", type: "♥", suit: "hearts", value: 13},

  {name: "A", type: "♠", suit: "spades", value: 1},
  {name: "2", type: "♠", suit: "spades", value: 2},
  {name: "3", type: "♠", suit: "spades", value: 3},
  {name: "4", type: "♠", suit: "spades", value: 4},
  {name: "5", type: "♠", suit: "spades", value: 5},
  {name: "6", type: "♠", suit: "spades", value: 6},
  {name: "7", type: "♠", suit: "spades", value: 7},
  {name: "8", type: "♠", suit: "spades", value: 8},
  {name: "9", type: "♠", suit: "spades", value: 9},
  {name: "10", type: "♠", suit: "spades", value: 10},
  {name: "J", type: "♠", suit: "spades", value: 11},
  {name: "Q", type: "♠", suit: "spades", value: 12},
  {name: "K", type: "♠", suit: "spades", value: 13},
]

module.exports = playingCards;
