const tajMahal = [
  {name: "4 Elephants", type: "Blue", suit: "star", value: 1, url: "https://furtivespy.com/images/tajmahal/blue_4e_star.jpg"},
  {name: "4 Elephants", type: "Blue", suit: "star", value: 1, url: "https://furtivespy.com/images/tajmahal/blue_4e_star.jpg"},
  {name: "Elephants & Viziers", type: "Blue", suit: "star", value: 2, url: "https://furtivespy.com/images/tajmahal/blue_2e2v_star.jpg"},
  {name: "Elephants & Viziers", type: "Blue", suit: "star", value: 2, url: "https://furtivespy.com/images/tajmahal/blue_2e2v_star.jpg"},
  {name: "Elephants & Viziers", type: "Blue", suit: "star", value: 2, url: "https://furtivespy.com/images/tajmahal/blue_2e2v_star.jpg"},
  {name: "Elephants & Princesses", type: "Blue", suit: "star", value: 3, url: "https://furtivespy.com/images/tajmahal/blue_2e2p_star.jpg"},
  {name: "Elephants & Princesses", type: "Blue", suit: "star", value: 3, url: "https://furtivespy.com/images/tajmahal/blue_2e2p_star.jpg"},
  {name: "Elephants & Princesses", type: "Blue", suit: "star", value: 3, url: "https://furtivespy.com/images/tajmahal/blue_2e2p_star.jpg"},
  {name: "Elephants & Monks", type: "Blue", suit: "star", value: 4, url: "https://furtivespy.com/images/tajmahal/blue_2e2m_star.jpg"},
  {name: "Elephants & Monks", type: "Blue", suit: "star", value: 4, url: "https://furtivespy.com/images/tajmahal/blue_2e2m_star.jpg"},
  {name: "Elephants & Monks", type: "Blue", suit: "star", value: 4, url: "https://furtivespy.com/images/tajmahal/blue_2e2m_star.jpg"},
  {name: "Elephants & Generals", type: "Blue", suit: "star", value: 5, url: "https://furtivespy.com/images/tajmahal/blue_2e2g_star.jpg"},
  {name: "Elephants & Generals", type: "Blue", suit: "star", value: 5, url: "https://furtivespy.com/images/tajmahal/blue_2e2g_star.jpg"},
  {name: "Elephants & Generals", type: "Blue", suit: "star", value: 5, url: "https://furtivespy.com/images/tajmahal/blue_2e2g_star.jpg"},
  {name: "Elephants & Grand Moguls", type: "Blue", suit: "star", value: 6, url: "https://furtivespy.com/images/tajmahal/blue_2e2t_star.jpg"},
  {name: "Elephants & Grand Moguls", type: "Blue", suit: "star", value: 6, url: "https://furtivespy.com/images/tajmahal/blue_2e2t_star.jpg"},
  {name: "Generals & Monks", type: "Blue", suit: "star", value: 7, url: "https://furtivespy.com/images/tajmahal/blue_2g2m_star.jpg"},
  {name: "Monks & Viziers", type: "Blue", suit: "star", value: 8, url: "https://furtivespy.com/images/tajmahal/blue_2m2v_star.jpg"},
  {name: "Grand Moguls & Generals", type: "Blue", suit: "star", value: 9, url: "https://furtivespy.com/images/tajmahal/blue_2t2g_star.jpg"},
  {name: "Grand Moguls & Princesses", type: "Blue", suit: "star", value: 10, url: "https://furtivespy.com/images/tajmahal/blue_2t2p_star.jpg"},
  {name: "Viziers & Princesses", type: "Blue", suit: "star", value: 11, url: "https://furtivespy.com/images/tajmahal/blue_2v2p_star.jpg"},
  {name: "4 Elephants", type: "Green", suit: "moon", value: 1, url: "https://furtivespy.com/images/tajmahal/green_4e_moon.jpg"},
  {name: "4 Elephants", type: "Green", suit: "moon", value: 1, url: "https://furtivespy.com/images/tajmahal/green_4e_moon.jpg"},
  {name: "Elephants & Viziers", type: "Green", suit: "moon", value: 2, url: "https://furtivespy.com/images/tajmahal/green_2e2v_moon.jpg"},
  {name: "Elephants & Viziers", type: "Green", suit: "moon", value: 2, url: "https://furtivespy.com/images/tajmahal/green_2e2v_moon.jpg"},
  {name: "Elephants & Viziers", type: "Green", suit: "moon", value: 2, url: "https://furtivespy.com/images/tajmahal/green_2e2v_moon.jpg"},
  {name: "Elephants & Princesses", type: "Green", suit: "moon", value: 3, url: "https://furtivespy.com/images/tajmahal/green_2e2p_moon.jpg"},
  {name: "Elephants & Princesses", type: "Green", suit: "moon", value: 3, url: "https://furtivespy.com/images/tajmahal/green_2e2p_moon.jpg"},
  {name: "Elephants & Princesses", type: "Green", suit: "moon", value: 3, url: "https://furtivespy.com/images/tajmahal/green_2e2p_moon.jpg"},
  {name: "Elephants & Monks", type: "Green", suit: "moon", value: 4, url: "https://furtivespy.com/images/tajmahal/green_2e2m_moon.jpg"},
  {name: "Elephants & Monks", type: "Green", suit: "moon", value: 4, url: "https://furtivespy.com/images/tajmahal/green_2e2m_moon.jpg"},
  {name: "Elephants & Monks", type: "Green", suit: "moon", value: 4, url: "https://furtivespy.com/images/tajmahal/green_2e2m_moon.jpg"},
  {name: "Elephants & Generals", type: "Green", suit: "moon", value: 5, url: "https://furtivespy.com/images/tajmahal/green_2e2g_moon.jpg"},
  {name: "Elephants & Generals", type: "Green", suit: "moon", value: 5, url: "https://furtivespy.com/images/tajmahal/green_2e2g_moon.jpg"},
  {name: "Elephants & Generals", type: "Green", suit: "moon", value: 5, url: "https://furtivespy.com/images/tajmahal/green_2e2g_moon.jpg"},
  {name: "Elephants & Grand Moguls", type: "Green", suit: "moon", value: 6, url: "https://furtivespy.com/images/tajmahal/green_2e2t_moon.jpg"},
  {name: "Elephants & Grand Moguls", type: "Green", suit: "moon", value: 6, url: "https://furtivespy.com/images/tajmahal/green_2e2t_moon.jpg"},
  {name: "Generals & Princesses", type: "Green", suit: "moon", value: 7, url: "https://furtivespy.com/images/tajmahal/green_2g2p_moon.jpg"},
  {name: "Princesses & Monks", type: "Green", suit: "moon", value: 8, url: "https://furtivespy.com/images/tajmahal/green_2p2m_moon.jpg"},
  {name: "Grand Moguls & Monks", type: "Green", suit: "moon", value: 9, url: "https://furtivespy.com/images/tajmahal/green_2t2m_moon.jpg"},
  {name: "Grand Moguls & Viziers", type: "Green", suit: "moon", value: 10, url: "https://furtivespy.com/images/tajmahal/green_2t2v_moon.jpg"},
  {name: "Viziers & Generals", type: "Green", suit: "moon", value: 11, url: "https://furtivespy.com/images/tajmahal/green_2v2g_moon.jpg"},
  {name: "4 Elephants", type: "Red", suit: "planet", value: 1, url: "https://furtivespy.com/images/tajmahal/red_4e_planet.jpg"},
  {name: "4 Elephants", type: "Red", suit: "planet", value: 1, url: "https://furtivespy.com/images/tajmahal/red_4e_planet.jpg"},
  {name: "Elephants & Viziers", type: "Red", suit: "planet", value: 2, url: "https://furtivespy.com/images/tajmahal/red_2e2v_planet.jpg"},
  {name: "Elephants & Viziers", type: "Red", suit: "planet", value: 2, url: "https://furtivespy.com/images/tajmahal/red_2e2v_planet.jpg"},
  {name: "Elephants & Viziers", type: "Red", suit: "planet", value: 2, url: "https://furtivespy.com/images/tajmahal/red_2e2v_planet.jpg"},
  {name: "Elephants & Princesses", type: "Red", suit: "planet", value: 3, url: "https://furtivespy.com/images/tajmahal/red_2e2p_planet.jpg"},
  {name: "Elephants & Princesses", type: "Red", suit: "planet", value: 3, url: "https://furtivespy.com/images/tajmahal/red_2e2p_planet.jpg"},
  {name: "Elephants & Princesses", type: "Red", suit: "planet", value: 3, url: "https://furtivespy.com/images/tajmahal/red_2e2p_planet.jpg"},
  {name: "Elephants & Monks", type: "Red", suit: "planet", value: 4, url: "https://furtivespy.com/images/tajmahal/red_2e2m_planet.jpg"},
  {name: "Elephants & Monks", type: "Red", suit: "planet", value: 4, url: "https://furtivespy.com/images/tajmahal/red_2e2m_planet.jpg"},
  {name: "Elephants & Monks", type: "Red", suit: "planet", value: 4, url: "https://furtivespy.com/images/tajmahal/red_2e2m_planet.jpg"},
  {name: "Elephants & Generals", type: "Red", suit: "planet", value: 5, url: "https://furtivespy.com/images/tajmahal/red_2e2g_planet.jpg"},
  {name: "Elephants & Generals", type: "Red", suit: "planet", value: 5, url: "https://furtivespy.com/images/tajmahal/red_2e2g_planet.jpg"},
  {name: "Elephants & Generals", type: "Red", suit: "planet", value: 5, url: "https://furtivespy.com/images/tajmahal/red_2e2g_planet.jpg"},
  {name: "Elephants & Grand Moguls", type: "Red", suit: "planet", value: 6, url: "https://furtivespy.com/images/tajmahal/red_2e2t_planet.jpg"},
  {name: "Elephants & Grand Moguls", type: "Red", suit: "planet", value: 6, url: "https://furtivespy.com/images/tajmahal/red_2e2t_planet.jpg"},
  {name: "Generals & Monks", type: "Red", suit: "planet", value: 7, url: "https://furtivespy.com/images/tajmahal/red_2g2m_planet.jpg"},
  {name: "Monks & Viziers", type: "Red", suit: "planet", value: 8, url: "https://furtivespy.com/images/tajmahal/red_2m2v_planet.jpg"},
  {name: "Grand Moguls & Generals", type: "Red", suit: "planet", value: 9, url: "https://furtivespy.com/images/tajmahal/red_2t2g_planet.jpg"},
  {name: "Grand Moguls & Princesses", type: "Red", suit: "planet", value: 10, url: "https://furtivespy.com/images/tajmahal/red_2t2p_planet.jpg"},
  {name: "Viziers & Princesses", type: "Red", suit: "planet", value: 11, url: "https://furtivespy.com/images/tajmahal/red_2v2p_planet.jpg"},
  {name: "4 Elephants", type: "Yellow", suit: "sun", value: 1, url: "https://furtivespy.com/images/tajmahal/yellow_4e_sun.jpg"},
  {name: "4 Elephants", type: "Yellow", suit: "sun", value: 1, url: "https://furtivespy.com/images/tajmahal/yellow_4e_sun.jpg"},
  {name: "Elephants & Viziers", type: "Yellow", suit: "sun", value: 2, url: "https://furtivespy.com/images/tajmahal/yellow_2e2v_sun.jpg"},
  {name: "Elephants & Viziers", type: "Yellow", suit: "sun", value: 2, url: "https://furtivespy.com/images/tajmahal/yellow_2e2v_sun.jpg"},
  {name: "Elephants & Viziers", type: "Yellow", suit: "sun", value: 2, url: "https://furtivespy.com/images/tajmahal/yellow_2e2v_sun.jpg"},
  {name: "Elephants & Princesses", type: "Yellow", suit: "sun", value: 3, url: "https://furtivespy.com/images/tajmahal/yellow_2e2p_sun.jpg"},
  {name: "Elephants & Princesses", type: "Yellow", suit: "sun", value: 3, url: "https://furtivespy.com/images/tajmahal/yellow_2e2p_sun.jpg"},
  {name: "Elephants & Princesses", type: "Yellow", suit: "sun", value: 3, url: "https://furtivespy.com/images/tajmahal/yellow_2e2p_sun.jpg"},
  {name: "Elephants & Monks", type: "Yellow", suit: "sun", value: 4, url: "https://furtivespy.com/images/tajmahal/yellow_2e2m_sun.jpg"},
  {name: "Elephants & Monks", type: "Yellow", suit: "sun", value: 4, url: "https://furtivespy.com/images/tajmahal/yellow_2e2m_sun.jpg"},
  {name: "Elephants & Monks", type: "Yellow", suit: "sun", value: 4, url: "https://furtivespy.com/images/tajmahal/yellow_2e2m_sun.jpg"},
  {name: "Elephants & Generals", type: "Yellow", suit: "sun", value: 5, url: "https://furtivespy.com/images/tajmahal/yellow_2e2g_sun.jpg"},
  {name: "Elephants & Generals", type: "Yellow", suit: "sun", value: 5, url: "https://furtivespy.com/images/tajmahal/yellow_2e2g_sun.jpg"},
  {name: "Elephants & Generals", type: "Yellow", suit: "sun", value: 5, url: "https://furtivespy.com/images/tajmahal/yellow_2e2g_sun.jpg"},
  {name: "Elephants & Grand Moguls", type: "Yellow", suit: "sun", value: 6, url: "https://furtivespy.com/images/tajmahal/yellow_2e2t_sun.jpg"},
  {name: "Elephants & Grand Moguls", type: "Yellow", suit: "sun", value: 6, url: "https://furtivespy.com/images/tajmahal/yellow_2e2t_sun.jpg"},
  {name: "Generals & Princesses", type: "Yellow", suit: "sun", value: 7, url: "https://furtivespy.com/images/tajmahal/yellow_2g2p_sun.jpg"},
  {name: "Princesses & Monks", type: "Yellow", suit: "sun", value: 8, url: "https://furtivespy.com/images/tajmahal/yellow_2p2m_sun.jpg"},
  {name: "Grand Moguls & Monks", type: "Yellow", suit: "sun", value: 9, url: "https://furtivespy.com/images/tajmahal/yellow_2t2m_sun.jpg"},
  {name: "Grand Moguls & Viziers", type: "Yellow", suit: "sun", value: 10, url: "https://furtivespy.com/images/tajmahal/yellow_2t2v_sun.jpg"},
  {name: "Viziers & Generals", type: "Yellow", suit: "sun", value: 11, url: "https://furtivespy.com/images/tajmahal/yellow_2v2g_sun.jpg"},
  {name: "Elephants", type: "White", suit: "none", value: 1, url: "https://furtivespy.com/images/tajmahal/white_2e.jpg"},
  {name: "Elephants", type: "White", suit: "none", value: 1, url: "https://furtivespy.com/images/tajmahal/white_2e.jpg"},
  {name: "Elephants", type: "White", suit: "none", value: 1, url: "https://furtivespy.com/images/tajmahal/white_2e.jpg"},
  {name: "Elephants", type: "White", suit: "none", value: 1, url: "https://furtivespy.com/images/tajmahal/white_2e.jpg"},
  {name: "Elephants", type: "White", suit: "none", value: 1, url: "https://furtivespy.com/images/tajmahal/white_2e.jpg"},
  {name: "Elephants", type: "White", suit: "none", value: 1, url: "https://furtivespy.com/images/tajmahal/white_2e.jpg"},
  {name: "Elephants", type: "White", suit: "none", value: 1, url: "https://furtivespy.com/images/tajmahal/white_2e.jpg"},
  {name: "Viziers", type: "White", suit: "none", value: 2, url: "https://furtivespy.com/images/tajmahal/white_2v.jpg"},
  {name: "Princesses", type: "White", suit: "none", value: 3, url: "https://furtivespy.com/images/tajmahal/white_2p.jpg"},
  {name: "Monks", type: "White", suit: "none", value: 4, url: "https://furtivespy.com/images/tajmahal/white_2m.jpg"},
  {name: "Generals", type: "White", suit: "none", value: 5, url: "https://furtivespy.com/images/tajmahal/white_2g.jpg"},
  {name: "Grand Moguls", type: "White", suit: "none", value: 6, url: "https://furtivespy.com/images/tajmahal/white_2t.jpg"},
];

module.exports = tajMahal;